---
title: "Supplementary Material for the Technical Comment to LaManna *et al*. 2017, Science"
author: "Lisa Hülsmann & Florian Hartig"
date: "February 15 2018"
output: 
  html_document: 
    keep_md: yes
    toc: no
---

This repository  provides code, simulation results, and explanations of the simulated scenarios for Hülsmann & Hartig (2018) **Comment on “Plant diversity increases with the strength of negative density dependence at the global scale”**. In review for *Science*. This paper is a technical comment on LaManna *et al*. 2017. *Science*.

The material is organized in four subfolders

* [**Fig1**](https://github.com/LisaHuelsmann/CommentTo-LaMannaEtAl-Science/tree/master/Fig1): this subfolder contains the materials necessary to reproduce Fig. 1 in Hülsmann & Hartig (2018)  
* [**Fig2**](https://github.com/LisaHuelsmann/CommentTo-LaMannaEtAl-Science/tree/master/Fig2): this subfolder contains the materials necessary to reproduce Fig. 2 in Hülsmann & Hartig (2018)  
* [**code**](https://github.com/LisaHuelsmann/CommentTo-LaMannaEtAl-Science/tree/master/code): this subfolder contains the R code used in Figs. 1,2
      + for the simulation null models, as well as an explanation of their motivation, 
      + and for the CNDD analyses using the Ricker and offset-power model
* [**data**](https://github.com/LisaHuelsmann/CommentTo-LaMannaEtAl-Science/tree/master/data): this subfolder contains the data preparation scripts, and should also contain the raw data of BCI, which must be independently requested at http://ctfs.si.edu/webatlas/datasets/bci/


For details on our analysis see [here](https://github.com/LisaHuelsmann/CommentTo-LaMannaEtAl-Science/tree/master/code).


